function DocumentWriteSafe(s) {
  try {
    document.write(s);
  } catch (err) {
    // alert(s + '  ---  ' + err.name.toString() + ':- ' + err.message);
  }
}

function AttachScript(url) {
  try {
    var e = document.createElement('script');
    e.setAttribute('language', 'javascript');
    e.setAttribute('type', 'text/javascript');
    e.setAttribute('src', url);
    var h = document.getElementsByTagName('head')[0];
    h.appendChild(e);
  } catch (err) {
    // alert('AttachScript: ' + url + '  ---  ' + err.name.toString() + ':- ' + err.message);
  }
}

function AttachStylesheet(url, media) {
  try {
    var e = document.createElement('link');
    e.setAttribute('rel', 'stylesheet');
    e.setAttribute('type', 'text/css');
    e.setAttribute('href', url);
    if (media.length > 0) {
      e.setAttribute('media', media);
    }
    document.getElementsByTagName('head')[0].appendChild(e);
  } catch (err) {
    // alert('AttachStylesheet: ' + url + '  ---  ' + err.name.toString() + ':- ' + err.message);
  }
}

if (typeof jQuery == 'undefined') {
  AttachScript('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js');
}
AttachStylesheet('https://www.avistautilities.com/Style%20Library/en-US/Core%20Styles/pageLayouts.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/1033/styles/core.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/base.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/home.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/header.css?Version=10360', 'screen');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/footer.css?Version=10360', 'screen');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/transactions.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/sidenav.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/spfixes.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/print.css?Version=10360', 'print');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/HtmlEditorCustomStyles.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/section_blue.css?Version=10360', '');
AttachStylesheet('https://www.avistautilities.com/_layouts/avista/css/wrapExt.css?Version=10360', '');
AttachScript('https://www.avistautilities.com/_layouts/avista/js/expando.js?Version=10360');
AttachScript('https://www.avistautilities.com/_layouts/avista/js/hoverGraphics.js?Version=10360');
AttachScript('https://www.avistautilities.com/_layouts/avista/js/sidenav.js?Version=10360');
AttachScript('https://www.avistautilities.com/_layouts/avista/js/wrapExt.js?Version=10360');
AttachScript('https://www.avistautilities.com/_layouts/avista/js/base.js?Version=10360');
AttachScript('https://www.avistautilities.com/_layouts/1033/init.js?Version=10360');
AttachScript('https://www.avistautilities.com/_layouts/1033/core.js?Version=10360');
AttachScript('https://www.avistautilities.com/_layouts/1033/InitNoPresence.js?Version=10360');
AttachScript('https://www.avistautilities.com/_layouts/avista/js/jquery.watermark-3.1.3.min.js?Version=10360');
DocumentWriteSafe('<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />');
DocumentWriteSafe('<meta http-equiv="Pragma" content="no-cache" />');
DocumentWriteSafe('<meta http-equiv="Expires" content="0" />');
DocumentWriteSafe('<link rel="shortcut icon" href="https://www.avistautilities.com/_layouts/Avista/Images/favicon.ico" />');
DocumentWriteSafe('<DIV id=body>');
DocumentWriteSafe('<TABLE id=main border=0 cellSpacing=0 borderColor=green cellPadding=0>');
DocumentWriteSafe('  <TBODY>');
DocumentWriteSafe('  <TR>');
DocumentWriteSafe('    <TD id=maincell>');
DocumentWriteSafe('      <DIV style="DISPLAY: none"><MAP name=header><AREA ');
DocumentWriteSafe('        href="https://www.avistautilities.com/pages/default.aspx" shape=RECT ');
DocumentWriteSafe('        coords="581, 30, 740, 80"><AREA noHref=nohref shape=DEFAULT></MAP></DIV>');
DocumentWriteSafe('		 <div id="headerContainer"><DIV style="float:left; height: 114px; width: 355px; background-color: #ffffff; text-align: left; margin-bottom: 0px; background: url(https://www.avistautilities.com/_layouts/avista/images/AskAvista/header-logo-star.png) top left no-repeat"></DIV>');
DocumentWriteSafe('      <DIV id=tertiaryNav class=tertiaryNav><A ');
DocumentWriteSafe('      id=ctl00_ctlHeader_hypResidentialHome class=tertiarySelected ');
DocumentWriteSafe('      href="https://www.avistautilities.com/residential/pages/default.aspx">Residential ');
DocumentWriteSafe('      Home</A> | <A ');
DocumentWriteSafe('      id=ctl00_ctlHeader_hypBusinessHome ');
DocumentWriteSafe('      href="https://www.avistautilities.com/business/pages/default.aspx">Business Home</A> | <A ');
DocumentWriteSafe('      id=ctl00_ctlHeader_hypInside ');
DocumentWriteSafe('      href="https://www.avistautilities.com/inside/pages/default.aspx">Inside Avista</A> | <A ');
DocumentWriteSafe('      id=ctl00_ctlHeader_hypContactUs ');
DocumentWriteSafe('      href="https://www.avistautilities.com/contact/pages/default.aspx">Contact Us</A> | <A ');
DocumentWriteSafe('      id=ctl00_ctlHeader_hypQuestions  ');
DocumentWriteSafe('      href="https://www.avistautilities.com/questions/pages/default.aspx">Questions?</A> ');
DocumentWriteSafe('       | ');
DocumentWriteSafe('      <A id=ctl00_ctlHeader_hypSignIn href="https://www.avistautilities.com/_layouts/Avista/SignOut.aspx">Sign-Out</A>');
DocumentWriteSafe('      </DIV></div><br style="clear: both;" />');
DocumentWriteSafe('      <DIV id=ctl00_ctlHeader_pnlMainNav>');
DocumentWriteSafe('      <TABLE id=mainNav border=0 cellSpacing=0 cellPadding=0 width="100%">');
DocumentWriteSafe('        <TBODY>');
DocumentWriteSafe('        <TR>');
DocumentWriteSafe('          <TD class=mainNavFill_wrap>');
DocumentWriteSafe('            <TABLE id=zz1_Menu1 ');
DocumentWriteSafe('            class="mainNavMenu_wrap firstLevelItem zz1_Menu1_5 zz1_Menu1_2" border=0 ');
DocumentWriteSafe('            cellSpacing=0 cellPadding=0>');
DocumentWriteSafe('              <TBODY>');
DocumentWriteSafe('              <TR>');
DocumentWriteSafe('<td id="zz1_Menu1n0" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverStatic(this)">');
DocumentWriteSafe('<table class="firstLevelItem zz1_Menu1_4" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody> ');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="white-space: nowrap;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 firstLevelItem zz1_Menu1_3" href="https://www.avistautilities.com/account/Pages/default.aspx" style="border-style: none; font-size: 1em;">My Account</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('<td style="width: 3px;"/>');
DocumentWriteSafe('<td id="zz1_Menu1n1" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverStatic(this)">');
DocumentWriteSafe('<table class="firstLevelItem zz1_Menu1_4" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody> ');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="white-space: nowrap;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 firstLevelItem zz1_Menu1_3" href="https://www.avistautilities.com/services/Pages/default.aspx" style="border-style: none; font-size: 1em;">Services &amp; Pricing</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('<td style="width: 3px;"/>');
DocumentWriteSafe('<td id="zz1_Menu1n2" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverStatic(this)">');
DocumentWriteSafe('<table class="firstLevelItem zz1_Menu1_4" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody> ');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="white-space: nowrap;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 firstLevelItem zz1_Menu1_3" href="https://www.avistautilities.com/savings/Pages/default.aspx" style="border-style: none; font-size: 1em;">Energy Savings</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('<td style="width: 3px;"/>');
DocumentWriteSafe('<td id="zz1_Menu1n3" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverStatic(this)">');
DocumentWriteSafe('<table class="firstLevelItem zz1_Menu1_4" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody> ');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="white-space: nowrap;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 firstLevelItem zz1_Menu1_3" href="https://www.avistautilities.com/safety/Pages/default.aspx" style="border-style: none; font-size: 1em;">Your Safety</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('<td style="width: 3px;"/>');
DocumentWriteSafe('<td id="zz1_Menu1n4" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverStatic(this)">');
DocumentWriteSafe('<table class="firstLevelItem zz1_Menu1_4" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody> ');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="white-space: nowrap;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 firstLevelItem zz1_Menu1_3" href="https://www.avistautilities.com/environment/Pages/default.aspx" style="border-style: none; font-size: 1em;">Our Environment</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('<td style="width: 3px;"/>');
DocumentWriteSafe('<td id="zz1_Menu1n5" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverStatic(this)">');
DocumentWriteSafe('<table class="firstLevelItem zz1_Menu1_4" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody> ');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="white-space: nowrap;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 firstLevelItem zz1_Menu1_3" href="https://www.avistautilities.com/community/Pages/default.aspx" style="border-style: none; font-size: 1em;">Our Community</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('<td style="width: 3px;"/>');
DocumentWriteSafe('<td id="zz1_Menu1n6" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverStatic(this)">');
DocumentWriteSafe('<table class="firstLevelItem zz1_Menu1_4" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody> ');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="white-space: nowrap;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 firstLevelItem zz1_Menu1_3" href="https://www.avistautilities.com/community/blog" style="border-style: none; font-size: 1em;">Blog</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('<td style="width: 3px;"/>');
DocumentWriteSafe(' </TR></TBODY></TABLE>');
DocumentWriteSafe('            <DIV id=zz1_Menu1n0Items ');
DocumentWriteSafe('            class="zz1_Menu1_0 mainNavSubMenu zz1_Menu1_8">');
DocumentWriteSafe('            <TABLE border=0 cellSpacing=0 cellPadding=0>');
DocumentWriteSafe('                    <TBODY>');
DocumentWriteSafe('<tr id="zz1_Menu1n7" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/payoptions/Pages/default.aspx" style="border-style: none; font-size: 1em;">Pay Now</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n8" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.comhttp://www.avistainfo.com" style="border-style: none; font-size: 1em;">Bill Assistance</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n9" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/bill/Pages/default.aspx" style="border-style: none; font-size: 1em;">My Bill</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n10" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/payments/Pages/default.aspx" style="border-style: none; font-size: 1em;">My Payments</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n11" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/moving/Pages/default.aspx" style="border-style: none; font-size: 1em;">Moving?</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n12" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/update/Pages/default.aspx" style="border-style: none; font-size: 1em;">Update My Account</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n13" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/billoptions/Pages/default.aspx" style="border-style: none; font-size: 1em;">Billing Options</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n14" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/payoptions/Pages/default.aspx" style="border-style: none; font-size: 1em;">Payment Options</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n15" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/landlord/Pages/default.aspx" style="border-style: none; font-size: 1em;">Manage Properties</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n16" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/inserts/_layouts/avista/billinserts.aspx" style="border-style: none; font-size: 1em;">Bill Inserts </a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n17" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/account/smartphone/Pages/default.aspx" style="border-style: none; font-size: 1em;">Avista&#39;s Mobile Website</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</div>');
DocumentWriteSafe('            <DIV id=zz1_Menu1n1Items ');
DocumentWriteSafe('            class="zz1_Menu1_0 mainNavSubMenu zz1_Menu1_8">');
DocumentWriteSafe('            <TABLE border=0 cellSpacing=0 cellPadding=0>');
DocumentWriteSafe('                    <TBODY>');
DocumentWriteSafe('<tr id="zz1_Menu1n18" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/gas/Pages/default.aspx" style="border-style: none; font-size: 1em;">Natural Gas Services</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n19" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/electricity/Pages/default.aspx" style="border-style: none; font-size: 1em;">Electricity Services</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n20" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/business/builder" style="border-style: none; font-size: 1em;">Builder Services</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n21" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/renewable/Pages/default.aspx" style="border-style: none; font-size: 1em;">Renewable Energy Generation</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n22" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/energypricing/Pages/default.aspx" style="border-style: none; font-size: 1em;">Energy Pricing</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n23" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/aboutrates/Pages/default.aspx" style="border-style: none; font-size: 1em;">About Rates</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n24" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/ratetreq/Pages/default.aspx" style="border-style: none; font-size: 1em;">Current Rate Requests</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n25" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/how/Pages/default.aspx" style="border-style: none; font-size: 1em;">How Energy Works</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n26" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/hwgc/Pages/default.aspx" style="border-style: none; font-size: 1em;">Housewarming Gift Certificate</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n27" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/services/transportation/Pages/default.aspx" style="border-style: none; font-size: 1em;">Transportation</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</div>');
DocumentWriteSafe('            <DIV id=zz1_Menu1n2Items ');
DocumentWriteSafe('            class="zz1_Menu1_0 mainNavSubMenu zz1_Menu1_8">');
DocumentWriteSafe('            <TABLE border=0 cellSpacing=0 cellPadding=0>');
DocumentWriteSafe('                    <TBODY>');
DocumentWriteSafe('<tr id="zz1_Menu1n28" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/savings/rebates/Pages/default.aspx" style="border-style: none; font-size: 1em;">Energy Efficiency Rebates</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n29" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/savings/tips/Pages/default.aspx" style="border-style: none; font-size: 1em;">Energy Saving Advice</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n30" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/savings/suite/Pages/default.aspx" style="border-style: none; font-size: 1em;">Energy Savings Tools</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n31" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/savings/outreach/Pages/default.aspx" style="border-style: none; font-size: 1em;">Energy Outreach</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n32" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/savings/assistance/Pages/default.aspx" style="border-style: none; font-size: 1em;">Energy Assistance Programs</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n33" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/savings/dsm/Pages/default.aspx" style="border-style: none; font-size: 1em;">What is DSM?</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</div>');
DocumentWriteSafe('            <DIV id=zz1_Menu1n3Items ');
DocumentWriteSafe('            class="zz1_Menu1_0 mainNavSubMenu zz1_Menu1_8">');
DocumentWriteSafe('            <TABLE border=0 cellSpacing=0 cellPadding=0>');
DocumentWriteSafe('                    <TBODY>');
DocumentWriteSafe('<tr id="zz1_Menu1n34" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/electric/Pages/default.aspx" style="border-style: none; font-size: 1em;">Electric Safety</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n35" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/naturalgas/Pages/default.aspx" style="border-style: none; font-size: 1em;">Natural Gas Safety</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n36" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/call/Pages/default.aspx" style="border-style: none; font-size: 1em;">Call 811 Before You Dig</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n37" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/outages/Pages/default.aspx" style="border-style: none; font-size: 1em;">Power Outages</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n38" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/dams/Pages/default.aspx" style="border-style: none; font-size: 1em;">Safety Around Dams</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n39" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/fire/Pages/default.aspx" style="border-style: none; font-size: 1em;">Fire Safety</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n40" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/vegetation/Pages/default.aspx" style="border-style: none; font-size: 1em;">Vegetation Management</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n41" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/kids/Pages/default.aspx" style="border-style: none; font-size: 1em;">Kid Central</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n42" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/safety/metertesting/Pages/default.aspx" style="border-style: none; font-size: 1em;">Meter Testing</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</div>');
DocumentWriteSafe('            <DIV id=zz1_Menu1n4Items ');
DocumentWriteSafe('            class="zz1_Menu1_0 mainNavSubMenu zz1_Menu1_8">');
DocumentWriteSafe('            <TABLE border=0 cellSpacing=0 cellPadding=0>');
DocumentWriteSafe('                    <TBODY>');
DocumentWriteSafe('<tr id="zz1_Menu1n43" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/environment/policy/Pages/default.aspx" style="border-style: none; font-size: 1em;">Environmental Policy</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n44" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/environment/ourpart/Pages/default.aspx" style="border-style: none; font-size: 1em;">Doing Our Part</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n45" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/environment/renewableenergy/Pages/default.aspx" style="border-style: none; font-size: 1em;">Renewable Energy</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n46" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/environment/climate/Pages/default.aspx" style="border-style: none; font-size: 1em;">Climate Change</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n47" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/environment/clarkfork/Pages/default.aspx" style="border-style: none; font-size: 1em;">Clark Fork Project</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n48" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/environment/raptor/Pages/default.aspx" style="border-style: none; font-size: 1em;">Raptor Education &amp; Protection</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n49" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/environment/spokaneriver/Pages/default.aspx" style="border-style: none; font-size: 1em;">Spokane River Project</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n50" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/environment/Pages/waterflow.aspx" style="border-style: none; font-size: 1em;">Weather and Water Flow Information</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</div>');
DocumentWriteSafe('            <DIV id=zz1_Menu1n5Items ');
DocumentWriteSafe('            class="zz1_Menu1_0 mainNavSubMenu zz1_Menu1_8">');
DocumentWriteSafe('            <TABLE border=0 cellSpacing=0 cellPadding=0>');
DocumentWriteSafe('                    <TBODY>');
DocumentWriteSafe('<tr id="zz1_Menu1n51" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/community/assistance/Pages/default.aspx" style="border-style: none; font-size: 1em;">Energy Assistance Programs</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n52" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/community/giving/Pages/default.aspx" style="border-style: none; font-size: 1em;">Giving Back</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('<tr id="zz1_Menu1n53" onmouseout="Menu_Unhover(this)" onkeyup="Menu_Key(this)" onmouseover="Menu_HoverDynamic(this)">');
DocumentWriteSafe('<td>');
DocumentWriteSafe('<table class="secondLevelItem zz1_Menu1_7" cellspacing="0" cellpadding="0" border="0" width="100%">');
DocumentWriteSafe('<tbody>');
DocumentWriteSafe('<tr>');
DocumentWriteSafe('<td style="width: 100%; white-space: nowrap; font-size: 11px ! important;">');
DocumentWriteSafe('<a class="zz1_Menu1_1 secondLevelItem zz1_Menu1_6" href="https://www.avistautilities.com/community/prosperity/Pages/default.aspx" style="border-style: none; font-size: 1em;">Economic Prosperity</a>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</td>');
DocumentWriteSafe('</tr>');
DocumentWriteSafe('</tbody>');
DocumentWriteSafe('</table>');
DocumentWriteSafe('</div>');
DocumentWriteSafe('  <A id=zz1_Menu1_SkipLink></A></TD>');
DocumentWriteSafe('          <TD class="mainNavFill_wrap tdsearchbox"></TD></TR></TBODY></TABLE></DIV>');
DocumentWriteSafe('    ');
DocumentWriteSafe('   <DIV id=mainContent>');
DocumentWriteSafe('     <DIV id=centerContent>');
DocumentWriteSafe('      <TABLE id=interiorTable border=0 cellSpacing=0 borderColor=red ');
DocumentWriteSafe('     cellPadding=0>');
DocumentWriteSafe('       <TBODY>   ');
DocumentWriteSafe('        <TR vAlign=top>');
DocumentWriteSafe('         <TD id=oneThirdContentLeft>');
DocumentWriteSafe('          <TABLE id="leftNav" border=0 ');
DocumentWriteSafe('           cellSpacing=0 cellPadding=0>');
DocumentWriteSafe('              <TBODY>');
DocumentWriteSafe('              <TR>');
DocumentWriteSafe('                <TD class=sNavLeftStretch>');
DocumentWriteSafe('                 </TD>');
DocumentWriteSafe('              <TD style="PADDING-RIGHT: 3px">');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon1" class="snavlevel1icon" >');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink1" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/Pages/default.aspx" target=""  id="level3text1" >My Account </a> ');
DocumentWriteSafe('     <div id="level21" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon2" class="snavlevel1icon" >');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink2" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/payoptions/Pages/default.aspx" target=""  id="level3text2" >Pay Now</a> ');
DocumentWriteSafe('     <div id="level22" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon3" class="snavlevel1icon" >');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink3" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.comhttp://www.avistainfo.com" target=""  id="level3text3" >Bill Assistance</a> ');
DocumentWriteSafe('     <div id="level23" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon4" class="snavlevel1icon" >');
DocumentWriteSafe('<img id="icon4" src="https://www.avistautilities.com/_layouts/avista/images/SideNav/sNav_arrow_right.gif" border="0" width="11" height="11" onclick="snav_toggleLevel2(\'4\')" ');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink4" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/bill/Pages/default.aspx" target=""  id="level3text4" >My Bill</a> ');
DocumentWriteSafe('     <div id="level24" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/bill/history/_layouts/Avista/Transactions/BillingHistory.aspx" title="" target=""  id="level341">- Billing History</a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/bill/analyzer/_layouts/Avista/Transactions/BillAnalyzer.aspx" title="" target=""  id="level342">- Bill Analyzer </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/bill/use/_layouts/Avista/Transactions/ReduceYourUse.aspx" title="" target=""  id="level343">- Online Energy Advisor</a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/bill/readyourbill/Pages/default.aspx" title="" target=""  id="level344">- Reading Your Bill </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/bill/readyourmeter/Pages/default.aspx" title="" target=""  id="level345">- Reading Your Meter </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon5" class="snavlevel1icon" >');
DocumentWriteSafe('<img id="icon5" src="https://www.avistautilities.com/_layouts/avista/images/SideNav/sNav_arrow_right.gif" border="0" width="11" height="11" onclick="snav_toggleLevel2(\'5\')" ');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink5" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/payments/Pages/default.aspx" target=""  id="level3text5" >My Payments </a> ');
DocumentWriteSafe('     <div id="level25" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/payments/PaymentHistory/_layouts/Avista/Transactions/PaymentHistory.aspx" title="" target=""  id="level352">- Payment History </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon6" class="snavlevel1icon" >');
DocumentWriteSafe('<img id="icon6" src="https://www.avistautilities.com/_layouts/avista/images/SideNav/sNav_arrow_right.gif" border="0" width="11" height="11" onclick="snav_toggleLevel2(\'6\')" ');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink6" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/moving/Pages/default.aspx" target=""  id="level3text6" >Moving? </a> ');
DocumentWriteSafe('     <div id="level26" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/moving/StartService/_layouts/avista/transactions/OpenService.aspx" title="" target=""  id="level361">- Start Service </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/moving/StopService/_layouts/Avista/transactions/CloseService.aspx" title="" target=""  id="level362">- Stop Service </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/moving/TransferService/_layouts/Avista/transactions/TransferService.aspx" title="" target=""  id="level363">- Transfer Service </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/moving/HighLowAverage/_layouts/avista/HighLowAverageBilling.aspx" title="" target=""  id="level364">- Estimated Monthly Average</a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon7" class="snavlevel1icon" >');
DocumentWriteSafe('<img id="icon7" src="https://www.avistautilities.com/_layouts/avista/images/SideNav/sNav_arrow_right.gif" border="0" width="11" height="11" onclick="snav_toggleLevel2(\'7\')" ');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink7" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/update/Pages/default.aspx" target=""  id="level3text7" >Update My Account </a> ');
DocumentWriteSafe('     <div id="level27" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/update/mail/_layouts/avista/membership/Update.aspx" title="" target=""  id="level371">- Change Email </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/update/password/_layouts/avista/membership/Update.aspx" title="" target=""  id="level372">- Change Password </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/update/address/_layouts/avista/transactions/UpdateAccountInformation.aspx" title="" target=""  id="level373">- Change Mailing Address </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/update/phone/_layouts/avista/transactions/UpdateAccountInformation.aspx?update=phone" title="" target=""  id="level374">- Change Phone Number </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/update/preferences/_layouts/avista/membership/SetCommunicationPreferences.aspx" title="" target=""  id="level375">- Communication Preferences </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/update/preferences/_layouts/avista/membership/OutageNotifications.aspx" title="" target=""  id="level376">- Outage Notifications</a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon8" class="snavlevel1icon" >');
DocumentWriteSafe('<img id="icon8" src="https://www.avistautilities.com/_layouts/avista/images/SideNav/sNav_arrow_right.gif" border="0" width="11" height="11" onclick="snav_toggleLevel2(\'8\')" ');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink8" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/billoptions/Pages/default.aspx" target=""  id="level3text8" >Billing Options </a> ');
DocumentWriteSafe('     <div id="level28" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/billoptions/ebill/_layouts/avista/transactions/ebillenrollment.aspx" title="" target=""  id="level381">- Avista eBill </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/billoptions/comfortlevelbilling/_layouts/avista/transactions/clbenrollment.aspx" title="" target=""  id="level382">- Comfort Level Billing </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/billoptions/masterbill/Pages/default.aspx" title="" target=""  id="level383">- Master Billing </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/_layouts/avista/transactions/projectsharepledge.aspx" title="" target=""  id="level384">- Project Share Pledge </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/services/renewable/wind/Pages/default.aspx" title="" target=""  id="level385">- Buck-A-Block Program </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon9" class="snavlevel1icon" >');
DocumentWriteSafe('<img id="icon9" src="https://www.avistautilities.com/_layouts/avista/images/SideNav/sNav_arrow_right.gif" border="0" width="11" height="11" onclick="snav_toggleLevel2(\'9\')" ');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink9" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/payoptions/Pages/default.aspx" target=""  id="level3text9" >Payment Options </a> ');
DocumentWriteSafe('     <div id="level29" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/payoptions/now/_layouts/avista/transactions/paybill.aspx?landing=true" title="" target=""  id="level391">- Pay Now </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/payoptions/person/_layouts/avista/PayStationSearch.aspx" title="" target=""  id="level392">- Pay in Person </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/payoptions/paybymail/Pages/default.aspx" title="" target=""  id="level393">- Pay by Mail </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/payoptions/payment/_layouts/avista/transactions/apsenrollment.aspx" title="" target=""  id="level394">- Automatic Payment </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/community/assistance/Pages/default.aspx" title="" target=""  id="level395">- Energy Assistance </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('<a class="snavlevel2" href="https://www.avistautilities.com/account/payoptions/arrangement/_layouts/avista/transactions/makepaymentarrangements.aspx" title="" target=""  id="level396">- Payment Arrangement </a> ');
DocumentWriteSafe('  <br /> ');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="Landlord work bench">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon10" class="snavlevel1icon" >');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink10" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/landlord/Pages/default.aspx" target=""  id="level3text10" >Manage Properties</a> ');
DocumentWriteSafe('     <div id="level210" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon11" class="snavlevel1icon" >');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink11" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/inserts/_layouts/avista/billinserts.aspx" target=""  id="level3text11" >Bill Inserts </a> ');
DocumentWriteSafe('     <div id="level211" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon12" class="snavlevel1icon" >');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink12" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/services/hwgc/Pages/default.aspx" target=""  id="level3text12" >Housewarming Gift Certificate</a> ');
DocumentWriteSafe('     <div id="level212" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
DocumentWriteSafe('<table id = "leftnav" cellpadding="0" cellspacing="0" border="0" width="100%" title="">');
DocumentWriteSafe(' <tr> ');
DocumentWriteSafe('  <td id="tdicon13" class="snavlevel1icon" >');
DocumentWriteSafe('   </td> ');
DocumentWriteSafe('  <td id="tdlink13" class="snavlevel1link"> ');
DocumentWriteSafe('     <a class="snavlevel1" href="https://www.avistautilities.com/account/smartphone/Pages/default.aspx" target=""  id="level3text13" >Avista&#39;s Mobile Website</a> ');
DocumentWriteSafe('     <div id="level213" class="snavlevel2 snavlevel2Off"  >');
DocumentWriteSafe('</div> ');
DocumentWriteSafe('</td> ');
DocumentWriteSafe('</tr> ');
DocumentWriteSafe('</table> ');
var levelID = new Array();
levelID[0] ="0,0";
var levelurl = new Array();
levelID[1] = "1,0";
levelurl[1] = "/account/pages/default.aspx";
levelID[2] = "2,0";
levelurl[2] = "/account/payoptions/pages/default.aspx";
levelID[3] = "3,0";
levelurl[3] = "http://www.avistainfo.com";
levelID[4] = "4,0";
levelurl[4] = "/account/bill/pages/default.aspx";
levelID[5] = "4,1";
levelurl[5] = "/account/bill/history/_layouts/avista/transactions/billinghistory.aspx";
levelID[6] = "4,2";
levelurl[6] = "/account/bill/analyzer/_layouts/avista/transactions/billanalyzer.aspx";
levelID[7] = "4,3";
levelurl[7] = "/account/bill/use/_layouts/avista/transactions/reduceyouruse.aspx";
levelID[8] = "4,4";
levelurl[8] = "/account/bill/readyourbill/pages/default.aspx";
levelID[9] = "4,5";
levelurl[9] = "/account/bill/readyourmeter/pages/default.aspx";
levelID[10] = "5,0";
levelurl[10] = "/account/payments/pages/default.aspx";
levelID[11] = "5,1";
levelurl[11] = "/account/payments/pendingpayments/_layouts/avista/transactions/viewpendingpayments.aspx";
levelID[12] = "5,2";
levelurl[12] = "/account/payments/paymenthistory/_layouts/avista/transactions/paymenthistory.aspx";
levelID[13] = "5,3";
levelurl[13] = "/account/payments/report/_layouts/avista/transactions/reportpaymentpaid.aspx";
levelID[14] = "6,0";
levelurl[14] = "/account/moving/pages/default.aspx";
levelID[15] = "6,1";
levelurl[15] = "/account/moving/startservice/_layouts/avista/transactions/openservice.aspx";
levelID[16] = "6,2";
levelurl[16] = "/account/moving/stopservice/_layouts/avista/transactions/closeservice.aspx";
levelID[17] = "6,3";
levelurl[17] = "/account/moving/transferservice/_layouts/avista/transactions/transferservice.aspx";
levelID[18] = "6,4";
levelurl[18] = "/account/moving/highlowaverage/_layouts/avista/highlowaveragebilling.aspx";
levelID[19] = "7,0";
levelurl[19] = "/account/update/pages/default.aspx";
levelID[20] = "7,1";
levelurl[20] = "/account/update/mail/_layouts/avista/membership/update.aspx";
levelID[21] = "7,2";
levelurl[21] = "/account/update/password/_layouts/avista/membership/update.aspx";
levelID[22] = "7,3";
levelurl[22] = "/account/update/address/_layouts/avista/transactions/updateaccountinformation.aspx";
levelID[23] = "7,4";
levelurl[23] = "/account/update/phone/_layouts/avista/transactions/updateaccountinformation.aspx?update=phone";
levelID[24] = "7,5";
levelurl[24] = "/account/update/preferences/_layouts/avista/membership/setcommunicationpreferences.aspx";
levelID[25] = "8,0";
levelurl[25] = "/account/billoptions/pages/default.aspx";
levelID[26] = "8,1";
levelurl[26] = "/account/billoptions/ebill/_layouts/avista/transactions/ebillenrollment.aspx";
levelID[27] = "8,2";
levelurl[27] = "/account/billoptions/comfortlevelbilling/_layouts/avista/transactions/clbenrollment.aspx";
levelID[28] = "8,3";
levelurl[28] = "/account/billoptions/masterbill/pages/default.aspx";
levelID[29] = "8,4";
levelurl[29] = "/account/_layouts/avista/transactions/projectsharepledge.aspx";
levelID[30] = "8,5";
levelurl[30] = "/services/renewable/wind/pages/default.aspx";
levelID[31] = "9,0";
levelurl[31] = "/account/payoptions/pages/default.aspx";
levelID[32] = "9,1";
levelurl[32] = "/account/payoptions/now/_layouts/avista/transactions/paybill.aspx?landing=true";
levelID[33] = "9,2";
levelurl[33] = "/account/payoptions/person/_layouts/avista/paystationsearch.aspx";
levelID[34] = "9,3";
levelurl[34] = "/account/payoptions/paybymail/pages/default.aspx";
levelID[35] = "9,4";
levelurl[35] = "/account/payoptions/payment/_layouts/avista/transactions/apsenrollment.aspx";
levelID[36] = "9,5";
levelurl[36] = "/community/assistance/pages/default.aspx";
levelID[37] = "9,6";
levelurl[37] = "/account/payoptions/arrangement/_layouts/avista/transactions/makepaymentarrangements.aspx";
levelID[38] = "10,0";
levelurl[38] = "/account/landlord/pages/default.aspx";
levelID[39] = "11,0";
levelurl[39] = "/account/inserts/_layouts/avista/billinserts.aspx";
levelID[40] = "12,0";
levelurl[40] = "/services/hwgc/pages/default.aspx";
levelID[41] = "13,0";
levelurl[41] = "/account/smartphone/pages/default.aspx";
DocumentWriteSafe('  </TD>');
DocumentWriteSafe(' <TD class=sNavRightStretch>');
DocumentWriteSafe('   </TD></TR></TBODY></TABLE>');
DocumentWriteSafe('<TABLE style="WIDTH: 100%" border=0 cellSpacing=0 cellPadding=0><!-- bottom row w/ curved images -->');
DocumentWriteSafe('   <TBODY>');
DocumentWriteSafe('   <TR>');
DocumentWriteSafe('   <TD style="WIDTH: 4px">');
DocumentWriteSafe('     </TD>');
DocumentWriteSafe('   <TD class=sNavBottomStretch>');
DocumentWriteSafe('      </TD>');
DocumentWriteSafe('    <TD style="WIDTH: 4px">');
DocumentWriteSafe('     </TD></TR></TBODY></TABLE>	');
DocumentWriteSafe(' <div style="margin-bottom: 10px;"></div>	');
DocumentWriteSafe('  <table cellpadding="0" cellspacing="0" border="0" width="100%">	');
DocumentWriteSafe('  <tr>	');
DocumentWriteSafe('   <td class="msgBoxTopStretch" colspan="3"></td>');
DocumentWriteSafe('  </tr>	');
DocumentWriteSafe('   <tr>	');
DocumentWriteSafe('    <td class="msgBoxLeftStretch"></td>	');
DocumentWriteSafe('     <td>    	');
DocumentWriteSafe(' 	<div id="ctl00_PlaceHolderMain_LeftRail1_pnlBusiness">	');
DocumentWriteSafe('      <table cellpadding="0" cellspacing="0" border="0">	');
DocumentWriteSafe('         <tr>	');
DocumentWriteSafe('            <td class="homeHeadline" style="padding-right: 5px;">Services For Your Business</td>	');
DocumentWriteSafe('               <td style="padding: 5px;"><a href="https://www.avistautilities.com/business/pages/default.aspx" onmouseover="goOn(\'services_go2\')" onmouseout="goOff(\'services_go2\')"><img id="services_go2" src="https://www.avistautilities.com/_layouts/avista/images/icons/services_go.gif" alt="GO" /></a></td>	');
DocumentWriteSafe('             </tr>	');
DocumentWriteSafe('          </table>	');
DocumentWriteSafe(' </div>	');
DocumentWriteSafe(' </td>	');
DocumentWriteSafe('    <td class="msgBoxRightStretch"></td>	');
DocumentWriteSafe('  </tr>	');
DocumentWriteSafe('  <tr>	');
DocumentWriteSafe('      <td class="msgBoxBottomStretch" colspan="3"></td>');
DocumentWriteSafe('  </tr>	');
DocumentWriteSafe(' </table>	');
DocumentWriteSafe(' <TD>	');
